CREATE DATABASE INTERNSHIP_PROJECT;
USE INTERNSHIP_PROJECT;

CREATE TABLE USER(EMAIL VARCHAR(100) PRIMARY KEY,PASSWORD VARCHAR(100),ROLE ENUM('STUDENT','FACULTY','ADMIN'),CHECK(EMAIL LIKE '%@GMAIL.COM'));
CREATE TABLE COURSE(COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,COURSE_NAME VARCHAR(100),DESCRIPTION VARCHAR(100),FEES DOUBLE,START_DATE DATE,END_DATE DATE,VIDEO_EXPIRE_DAYS INT);
CREATE TABLE STUDENT(REG_NO INT PRIMARY KEY auto_increment,NAME VARCHAR(100),EMAIL VARCHAR(100),FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),COURSE_ID INT,FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID),MOBILE_NO INT,PROFILE_PIC BLOB);
CREATE TABLE VIDEO(VIDEO_ID INT PRIMARY KEY auto_increment,COURSE_ID INT,FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID),TITLE VARCHAR(100),DESCRIPTION VARCHAR(100),YOUTUBE_URL VARCHAR(100),ADDED_AT DATE);


INSERT INTO USER VALUES('sunita@gmail.com','12345','student'),
('anita@gmail.com','23456','student'),
('sunil@gmail.com','78906','student');

